[extension]
name = "sns"
version = "0.1.0"
homepage = "https://github.com/dfinity/dfx-extensions"
authors = "DFINITY"
summary = "Toolkit to simulate decentralizing a dapp via SNS."
categories = ["sns", "nns"]
keywords = [
    "sns",
    "nns",
    "deployment",
]

[extension.subcommands]
config = { subcommands = ["create", "validate" ]}
deploy = {}
import = {}
download = {}
