[package]
name = "orbit"
version = "0.1.0"
authors.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
