---
name: Lint Code Base

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: lint:required
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Install cmake
        run: sudo apt install cmake && cmake --version

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          VALIDATE_RUST_2015: false # SL already lints 2018 and 2021
          VALIDATE_NATURAL_LANGUAGE: false # needs custom config
          VALIDATE_YAML: false # needs custom config
          VALIDATE_GITLEAKS: false # needs custom config
          FILTER_REGEX_EXCLUDE: 'e2e/bats.*'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
